name: kan_kan
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  ui: ^0.0.1
  flutter_dotenv: ^5.2.1
  moyasar: ^2.0.13
  supabase_flutter: ^2.8.0
  get_it: ^8.0.1
  helper: 1.0.0
  carousel_slider: ^5.0.0
  pinput: ^5.0.0
  lottie: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  device_preview: ^1.2.0


flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/images/logo/
    - assets/images/products-sample/
    - assets/animation/
    - .env
  fonts:
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal-Bold.ttf
