import 'package:kan_kan_admin/model/order_model.dart';

List<OrderModel> orderList = [
  OrderModel(
    orderNumber: 'ORD001',
    customerName: 'أحمد الحسن',
    price: 250.75,
    product: 'هاتف ذكي',
    orderDate: '2024-10-15',
    status: 'تم دفع',
    shipmentStatus: 'تم التوصيل',
  ),
  OrderModel(
    orderNumber: 'ORD002',
    customerName: 'فاطمة السيد',
    price: 499.99,
    product: 'حاسوب محمول',
    orderDate: '2024-10-12',
    status: 'ملغي',
    shipmentStatus: 'ملغي',
  ),
  OrderModel(
    orderNumber: 'ORD003',
    customerName: 'محمد علي',
    price: 199.99,
    product: 'سماعات رأس',
    orderDate: '2024-10-10',
    status: 'تم الدفع',
    shipmentStatus: 'تم التوصيل',
  ),
  OrderModel(
    orderNumber: 'ORD004',
    customerName: 'سارة نور',
    price: 89.99,
    product: 'سماعة بلوتوث',
    orderDate: '2024-10-17',
    status: 'تم الدفع',
    shipmentStatus: 'تم التوصيل',
  ),
  OrderModel(
    orderNumber: 'ORD005',
    customerName: 'خالد عبد الله',
    price: 599.00,
    product: 'جهاز ألعاب',
    orderDate: '2024-10-13',
    status: 'تم الدفع',
    shipmentStatus: 'في الطريق',
  ),
  OrderModel(
    orderNumber: 'ORD006',
    customerName: 'ليلى مصطفى',
    price: 349.49,
    product: 'جهاز لوحي',
    orderDate: '2024-10-11',
    status: 'تم الدفع',
    shipmentStatus: 'تم التوصيل',
  ),
  OrderModel(
    orderNumber: 'ORD007',
    customerName: 'ياسمين عبد الرحمن',
    price: 129.99,
    product: 'ساعة ذكية',
    orderDate: '2024-10-14',
    status: 'تم الدفع',
    shipmentStatus: 'قيد الانتظار',
  ),
  OrderModel(
    orderNumber: 'ORD008',
    customerName: 'طارق فضل الله',
    price: 899.99,
    product: 'تلفاز 4K',
    orderDate: '2024-10-09',
    status: 'تم الدفع',
    shipmentStatus: 'في الطريق',
  ),
  OrderModel(
    orderNumber: 'ORD009',
    customerName: 'نور عادل',
    price: 59.99,
    product: 'شاحن لاسلكي',
    orderDate: '2024-10-16',
    status: 'ملغي',
    shipmentStatus: 'ملغي',
  ),
  OrderModel(
    orderNumber: 'ORD010',
    customerName: 'إبراهيم مصطفى',
    price: 749.00,
    product: 'كاميرا',
    orderDate: '2024-10-08',
    status: 'تم الدفع',
    shipmentStatus: 'تم التوصيل',
  ),
];
