import 'package:kan_kan_admin/model/user_model.dart';

List<UserModel> userList = [
  UserModel(
    id: '001',
    email: 'ahmed.alhassan@example.com',
    name: 'أحمد الحسن',
    phoneNumber: '+201234567890',
    region: 'الشرق الأوسط',
  ),
  UserModel(
    id: '002',
    email: 'mohammed.ali@example.com',
    name: 'محمد علي',
    phoneNumber: '+971234567890',
    region: 'الخليج',
  ),
  UserModel(
    id: '003',
    email: 'fatima.alsayed@example.com',
    name: 'فاطمة السيد',
    phoneNumber: '+962345678901',
    region: 'بلاد الشام',
  ),
  UserModel(
    id: '004',
    email: 'omar.abdullah@example.com',
    name: 'عمر عبدالله',
    phoneNumber: '+966543210987',
    region: 'الخليج',
  ),
  UserModel(
    id: '005',
    email: 'sara.hussein@example.com',
    name: 'سارة حسين',
    phoneNumber: '+202345678901',
    region: 'شمال أفريقيا',
  ),
  UserModel(
    id: '006',
    email: 'layla.mostafa@example.com',
    name: 'ليلى مصطفى',
    phoneNumber: '+961123456789',
    region: 'بلاد الشام',
  ),
  UserModel(
    id: '007',
    email: 'khaled.farouk@example.com',
    name: 'خالد فاروق',
    phoneNumber: '+202112345678',
    region: 'الشرق الأوسط',
  ),
  UserModel(
    id: '008',
    email: 'hana.nour@example.com',
    name: 'هناء نور',
    phoneNumber: '+218987654321',
    region: 'شمال أفريقيا',
  ),
  UserModel(
    id: '009',
    email: 'yasmin.abdelrahman@example.com',
    name: 'ياسمين عبدالرحمن',
    phoneNumber: '+973321098765',
    region: 'الخليج',
  ),
  UserModel(
    id: '010',
    email: 'tariq.fadlallah@example.com',
    name: 'طارق فضل الله',
    phoneNumber: '+962134567890',
    region: 'بلاد الشام',
  ),
  UserModel(
    id: '011',
    email: 'mona.ibrahim@example.com',
    name: 'منى إبراهيم',
    phoneNumber: '+201987654321',
    region: 'الشرق الأوسط',
  ),
  UserModel(
    id: '012',
    email: 'abdelrahman.salah@example.com',
    name: 'عبدالرحمن صلاح',
    phoneNumber: '+965654321098',
    region: 'الخليج',
  ),
  UserModel(
    id: '013',
    email: 'salma.mahmoud@example.com',
    name: 'سلمى محمود',
    phoneNumber: '+212123456789',
    region: 'شمال أفريقيا',
  ),
  UserModel(
    id: '014',
    email: 'youssef.ahmed@example.com',
    name: 'يوسف أحمد',
    phoneNumber: '+973123456789',
    region: 'الخليج',
  ),
  UserModel(
    id: '015',
    email: 'amira.kamal@example.com',
    name: 'أميرة كمال',
    phoneNumber: '+201345678901',
    region: 'الشرق الأوسط',
  ),
  UserModel(
    id: '016',
    email: 'samir.hassan@example.com',
    name: 'سمير حسن',
    phoneNumber: '+962234567890',
    region: 'بلاد الشام',
  ),
  UserModel(
    id: '017',
    email: 'noor.adel@example.com',
    name: 'نور عادل',
    phoneNumber: '+212987654321',
    region: 'شمال أفريقيا',
  ),
  UserModel(
    id: '018',
    email: 'hassan.ismail@example.com',
    name: 'حسن إسماعيل',
    phoneNumber: '+965321098765',
    region: 'الخليج',
  ),
  UserModel(
    id: '019',
    email: 'zainab.salim@example.com',
    name: 'زينب سليم',
    phoneNumber: '+202765432109',
    region: 'الشرق الأوسط',
  ),
  UserModel(
    id: '020',
    email: 'ibrahim.mustafa@example.com',
    name: 'إبراهيم مصطفى',
    phoneNumber: '+961987654321',
    region: 'بلاد الشام',
  ),
];
