import 'package:kan_kan_admin/model/product_model.dart';
List<ProductModel> productsList = [
  ProductModel(
    id: 'a1b2c3d4',
    productName: 'هاتف ذكي',
    factory: 'شركة الإلكترونيات',
    wight: 200,
    hight: 150,
    width: 75,
    length: 8,
    modelNumber: 'XYZ123',
    description: 'هاتف ذكي مزود بشاشة عالية الدقة وكاميرا ممتازة.',
  ),
  ProductModel(
    id: 'e5f6g7h8',
    productName: 'كمبيوتر محمول',
    factory: 'شركة الحواسيب',
    wight: 1500,
    hight: 20,
    width: 300,
    length: 200,
    modelNumber: 'ABC456',
    description: 'كمبيوتر محمول عالي الأداء للأعمال والدراسة.',
  ),
  ProductModel(
    id: 'i9j0k1l2',
    productName: 'ثلاجة',
    factory: 'شركة الأجهزة المنزلية',
    wight: 60000,
    hight: 1800,
    width: 600,
    length: 700,
    modelNumber: 'FRG789',
    description: 'ثلاجة عصرية بتقنية التبريد الذكي وحجم كبير.',
  ),
  ProductModel(
    id: 'm3n4o5p6',
    productName: 'غسالة',
    factory: 'شركة الأجهزة المنزلية',
    wight: 70000,
    hight: 850,
    width: 600,
    length: 600,
    modelNumber: 'WASH001',
    description: 'غسالة أوتوماتيكية مع وظائف متقدمة لتنظيف الملابس.',
  ),
  ProductModel(
    id: 'q7r8s9t0',
    productName: 'جهاز تلفاز',
    factory: 'شركة التلفزيونات',
    wight: 12000,
    hight: 750,
    width: 1200,
    length: 50,
    modelNumber: 'TV004',
    description: 'جهاز تلفاز ذكي بدقة 4K وشاشة كبيرة.',
  ),
];
