import 'package:kan_kan_admin/model/user_model.dart';

List<UserModel> userList = [
  UserModel(
    id: '001',
    email: 'john.doe@example.com',
    name: 'John Doe',
    phoneNumber: '+1234567890',
    region: 'North America',
  ),
  UserModel(
    id: '0023',
    email: 'jane.smith@example.com',
    name: 'Jane Smith',
    phoneNumber: '+0987654321',
    region: 'Europe',
  ),
  UserModel(
    id: '0030',
    email: 'michael.lee@example.com',
    name: 'Michael Lee',
    phoneNumber: '+1122334455',
    region: 'Asia',
  ),
  UserModel(
    id: '004',
    email: 'sara.kim@example.com',
    name: 'Sara Kim',
    phoneNumber: '+6677889900',
    region: 'South America',
  ),
  UserModel(
    id: '005',
    email: 'david.wang@example.com',
    name: 'David Wang',
    phoneNumber: '+4455667788',
    region: 'Australia',
  ),
  UserModel(
    id: '006',
    email: 'alex.jones@example.com',
    name: 'Alex Jones',
    phoneNumber: '+12125551234',
    region: 'North America',
  ),
  UserModel(
    id: '007',
    email: 'emma.watson@example.com',
    name: 'Emma Watson',
    phoneNumber: '+441234567890',
    region: 'Europe',
  ),
  UserModel(
    id: '008',
    email: 'liam.johnson@example.com',
    name: 'Liam Johnson',
    phoneNumber: '+8612345678901',
    region: 'Asia',
  ),
  UserModel(
    id: '009',
    email: 'maria.garcia@example.com',
    name: 'Maria Garcia',
    phoneNumber: '+552112345678',
    region: 'South America',
  ),
  UserModel(
    id: '010',
    email: 'oliver.brown@example.com',
    name: 'Oliver Brown',
    phoneNumber: '+61234567890',
    region: 'Australia',
  ),
  UserModel(
    id: '011',
    email: 'noah.davis@example.com',
    name: 'Noah Davis',
    phoneNumber: '+15123456789',
    region: 'North America',
  ),
  UserModel(
    id: '012',
    email: 'ava.white@example.com',
    name: 'Ava White',
    phoneNumber: '+331234567890',
    region: 'Europe',
  ),
  UserModel(
    id: '013',
    email: 'ethan.green@example.com',
    name: 'Ethan Green',
    phoneNumber: '+919876543210',
    region: 'Asia',
  ),
  UserModel(
    id: '014',
    email: 'sofia.martinez@example.com',
    name: 'Sofia Martinez',
    phoneNumber: '+571234567890',
    region: 'South America',
  ),
  UserModel(
    id: '015',
    email: 'harper.miller@example.com',
    name: 'Harper Miller',
    phoneNumber: '+61456789123',
    region: 'Australia',
  ),
  UserModel(
    id: '016',
    email: 'william.johnson@example.com',
    name: 'William Johnson',
    phoneNumber: '+19123456789',
    region: 'North America',
  ),
  UserModel(
    id: '017',
    email: 'isabella.moore@example.com',
    name: 'Isabella Moore',
    phoneNumber: '+441234567890',
    region: 'Europe',
  ),
  UserModel(
    id: '018',
    email: 'james.clark@example.com',
    name: 'James Clark',
    phoneNumber: '+861234567890',
    region: 'Asia',
  ),
  UserModel(
    id: '019',
    email: 'mia.rodriguez@example.com',
    name: 'Mia Rodriguez',
    phoneNumber: '+552123456789',
    region: 'South America',
  ),
  UserModel(
    id: '020',
    email: 'elijah.wilson@example.com',
    name: 'Elijah Wilson',
    phoneNumber: '+61456789101',
    region: 'Australia',
  ),
];
