name: kan_kan_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_dotenv: ^5.1.0
  get_it: ^8.0.1
  supabase_flutter: ^2.8.0
  ui: ^0.0.1
  helper: 1.0.0
  calendar_date_picker2: ^1.1.7
  file_picker: ^8.1.3
  fl_chart: ^0.69.0
  dio: ^5.7.0
  cached_network_image: ^3.4.1
  carousel_slider: ^5.0.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/
    - assets/images/
    - assets/images/logo/
    - assets/images/products-sample/
    - .env
  fonts:
     - family: Tajawal
       fonts:
         - asset: assets/fonts/Tajawal-Bold.ttf